---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinnothera
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
      - configmaps
    verbs:
      - get
      - list
      - watch
