---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sns-sqs-config  # Required, must be exactly 'sns-sqs-config'
  namespace: default  # Required, must match project name
  annotations:
    app-env: local  # Optional. If included, must be one of: "qa", "dev", "prod", "local"
data:
  yaml-template: |  # YAML Format
    ---
    <(queue-name)>:
      topics:
        - <(topic-name-1)>
        - <(topic-name-2)>
    unsubscribed:
      topics:
        - <(topic-name-1)>
        - <(topic-name-2)>
  json-template: |  # JSON Format
    {
      "<(queue-name)>": {
        "topics": [
          "<(topic-name-1)>",
          "<(topic-name-2)>"
        ]
      },
      "unsubscribed": {
        "topics": [
          "<(topic-name-1)>",
          "<(topic-name-2)>"
        ]
      }
    }
