#######################################
#        Cargo-Specific Options        #
#######################################

target-applies-to-host = false


#######################################
#       Target-Specific Options        #
#######################################

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-unknown-linux-gnu-gcc"

#[target.aarch64-unknown-linux-gnu]
#linker = "aarch64-unknown-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

# [target.wasm32-wasi]

# [target.wasm32-unknown-unknown]

# [target.wasm32-unknown-emscripten]

# [target.x86_64-unknown-linux-musl]

# [target.aarch64-unknown-linux-musl]


